name: Check
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  e2etest:
    name: e2etest
    runs-on: ubuntu-20.04
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
      - name: Run deployment script
        run: |
            pip install -r requirements/requirements-dev.txt
            modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
            modal serve src.app &
            python tests/e2e_test.py
